from __future__ import annotations

from . import __version__
from .errors import VerificationError
from .kir import Instruction, KIRFunction, KIRModule, verify

LLVM_TYPE = {"Int": "i64", "Bool": "i1"}

COMPARE_PREDICATE = {
    "icmp.eq": "eq",
    "icmp.ne": "ne",
    "icmp.slt": "slt",
    "icmp.sle": "sle",
    "icmp.sgt": "sgt",
    "icmp.sge": "sge",
}

CHECKED_HELPER = {
    "iadd.checked": "@kofu.checked.add.i64",
    "isub.checked": "@kofu.checked.sub.i64",
    "imul.checked": "@kofu.checked.mul.i64",
    "idiv.checked": "@kofu.checked.div.i64",
    "irem.checked": "@kofu.checked.rem.i64",
}


def emit_llvm(module: KIRModule, source_name: str = "module.kofu") -> str:
    verify(module)
    main = next((function for function in module.functions if function.name == "main"), None)
    if main is None or main.params or main.return_type != "Int":
        raise VerificationError("LLVM emitter: executable module must define fn main() -> Int")
    lines = [
        f"; Generated by KofuMini {__version__}",
        f'source_filename = "{llvm_string(source_name)}"',
        "",
        '@.fmt.i64 = private unnamed_addr constant [6 x i8] c"%lld\\0A\\00", align 1',
        "declare i32 @printf(ptr, ...)",
        "declare void @llvm.trap() cold noreturn nounwind",
        "declare { i64, i1 } @llvm.sadd.with.overflow.i64(i64, i64)",
        "declare { i64, i1 } @llvm.ssub.with.overflow.i64(i64, i64)",
        "declare { i64, i1 } @llvm.smul.with.overflow.i64(i64, i64)",
        "",
        CHECKED_RUNTIME.strip(),
        "",
    ]
    for function in module.functions:
        lines.append(emit_function(function))
        lines.append("")
    lines.extend(
        [
            "define i32 @main() {",
            "entry:",
            "  %result = call i64 @kofu.fn.main()",
            "  %exit_code = trunc i64 %result to i32",
            "  ret i32 %exit_code",
            "}",
            "",
        ]
    )
    return "\n".join(lines).rstrip() + "\n"


def llvm_string(value: str) -> str:
    """Escape arbitrary UTF-8 bytes for an LLVM quoted string."""
    parts: list[str] = []
    for byte in value.encode("utf-8"):
        if 0x20 <= byte <= 0x7E and byte not in {ord('"'), ord("\\")}:
            parts.append(chr(byte))
        else:
            parts.append(f"\\{byte:02X}")
    return "".join(parts)


def emit_function(function: KIRFunction) -> str:
    params = ", ".join(f"{LLVM_TYPE[param.type_name]} {param.value}" for param in function.params)
    lines = [f"define {LLVM_TYPE[function.return_type]} @kofu.fn.{function.name}({params}) {{"]
    for block in function.blocks:
        lines.append(f"{block.label}:")
        for instruction in block.instructions:
            lines.extend(emit_instruction(instruction))
        terminator = block.terminator
        assert terminator is not None
        if terminator.op == "return":
            lines.append(f"  ret {LLVM_TYPE[function.return_type]} {terminator.args[0]}")
        elif terminator.op == "jump":
            lines.append(f"  br label %{terminator.args[0]}")
        elif terminator.op == "branch":
            lines.append(
                f"  br i1 {terminator.args[0]}, label %{terminator.args[1]}, "
                f"label %{terminator.args[2]}"
            )
        else:
            raise AssertionError(terminator.op)
    lines.append("}")
    return "\n".join(lines)


def emit_instruction(instruction: Instruction) -> list[str]:
    op = instruction.op
    result = instruction.result
    if op == "const":
        assert result and instruction.type_name
        value = instruction.attrs["value"]
        if instruction.type_name == "Int":
            return [f"  {result} = add i64 0, {value}"]
        literal = "true" if value else "false"
        return [f"  {result} = xor i1 false, {literal}"]
    if op in CHECKED_HELPER:
        assert result
        left, right = instruction.args
        return [f"  {result} = call i64 {CHECKED_HELPER[op]}(i64 {left}, i64 {right})"]
    if op in COMPARE_PREDICATE:
        assert result
        left, right = instruction.args
        operand_type = LLVM_TYPE[instruction.attrs["operand_type"]]
        return [f"  {result} = icmp {COMPARE_PREDICATE[op]} {operand_type} {left}, {right}"]
    if op == "bool.not":
        assert result
        return [f"  {result} = xor i1 {instruction.args[0]}, true"]
    if op == "call":
        assert result and instruction.type_name
        callee = instruction.attrs["callee"]
        rendered_args = ", ".join(
            f"{LLVM_TYPE[arg_type]} {arg}"
            for arg_type, arg in zip(instruction.attrs["arg_types"], instruction.args, strict=True)
        )
        return [
            f"  {result} = call {LLVM_TYPE[instruction.type_name]} @kofu.fn.{callee}({rendered_args})"
        ]
    if op == "phi":
        assert result and instruction.type_name
        llvm_type = LLVM_TYPE[instruction.type_name]
        incoming = ", ".join(
            f"[ {value}, %{label} ]" for label, value in instruction.attrs["incoming"]
        )
        return [f"  {result} = phi {llvm_type} {incoming}"]
    if op == "print.i64":
        return [
            "  call i32 (ptr, ...) @printf("
            "ptr getelementptr inbounds ([6 x i8], ptr @.fmt.i64, i64 0, i64 0), "
            f"i64 {instruction.args[0]})"
        ]
    raise AssertionError(op)


CHECKED_RUNTIME = r"""
define internal i64 @kofu.checked.add.i64(i64 %left, i64 %right) {
entry:
  %pair = call { i64, i1 } @llvm.sadd.with.overflow.i64(i64 %left, i64 %right)
  %value = extractvalue { i64, i1 } %pair, 0
  %overflow = extractvalue { i64, i1 } %pair, 1
  br i1 %overflow, label %trap, label %ok
trap:
  call void @llvm.trap()
  unreachable
ok:
  ret i64 %value
}

define internal i64 @kofu.checked.sub.i64(i64 %left, i64 %right) {
entry:
  %pair = call { i64, i1 } @llvm.ssub.with.overflow.i64(i64 %left, i64 %right)
  %value = extractvalue { i64, i1 } %pair, 0
  %overflow = extractvalue { i64, i1 } %pair, 1
  br i1 %overflow, label %trap, label %ok
trap:
  call void @llvm.trap()
  unreachable
ok:
  ret i64 %value
}

define internal i64 @kofu.checked.mul.i64(i64 %left, i64 %right) {
entry:
  %pair = call { i64, i1 } @llvm.smul.with.overflow.i64(i64 %left, i64 %right)
  %value = extractvalue { i64, i1 } %pair, 0
  %overflow = extractvalue { i64, i1 } %pair, 1
  br i1 %overflow, label %trap, label %ok
trap:
  call void @llvm.trap()
  unreachable
ok:
  ret i64 %value
}

define internal i64 @kofu.checked.div.i64(i64 %left, i64 %right) {
entry:
  %is_zero = icmp eq i64 %right, 0
  br i1 %is_zero, label %trap, label %overflow.check
overflow.check:
  %is_min = icmp eq i64 %left, -9223372036854775808
  %is_neg_one = icmp eq i64 %right, -1
  %is_overflow = and i1 %is_min, %is_neg_one
  br i1 %is_overflow, label %trap, label %ok
trap:
  call void @llvm.trap()
  unreachable
ok:
  %value = sdiv i64 %left, %right
  ret i64 %value
}

define internal i64 @kofu.checked.rem.i64(i64 %left, i64 %right) {
entry:
  %is_zero = icmp eq i64 %right, 0
  br i1 %is_zero, label %trap, label %overflow.check
overflow.check:
  %is_min = icmp eq i64 %left, -9223372036854775808
  %is_neg_one = icmp eq i64 %right, -1
  %is_overflow = and i1 %is_min, %is_neg_one
  br i1 %is_overflow, label %trap, label %ok
trap:
  call void @llvm.trap()
  unreachable
ok:
  %value = srem i64 %left, %right
  ret i64 %value
}
"""
